"""criacao da tabela bacias hidrografias e tabela pivo

Revision ID: 3aa4d410c819
Revises: b6731a367148
Create Date: 2022-04-20 08:21:20.217909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa4d410c819'
down_revision = 'b6731a367148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacias_hidrograficas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('bacias_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bacia_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bacia_id'], ['bacias_hidrograficas.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bacias_estados')
    op.drop_table('bacias_hidrograficas')
    # ### end Alembic commands ###
