"""criação da tabela regiao e FK regiao_id

Revision ID: b6731a367148
Revises: 75bc37b1eef1
Create Date: 2022-04-18 22:56:01.872268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6731a367148'
down_revision = '75bc37b1eef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('numero_estados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('estados', sa.Column('regiao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estados', 'regioes', ['regiao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estados', type_='foreignkey')
    op.drop_column('estados', 'regiao_id')
    op.drop_table('regioes')
    # ### end Alembic commands ###
